"""Caddy front for the domain branch of the server.

The self-signed branch puts wstunnel itself on 443 with a certificate that no
chain validates and that no real deployment would ever issue — fine on a network
that only blocks UDP, useless against one that inspects TLS. This module is the
other branch: Caddy holds 443 with a Let's Encrypt certificate, serves an
ordinary web page at ``/``, and only proxies to wstunnel — which has moved to a
loopback plain-WebSocket listener — on the secret upgrade path, and only for
requests that are actually WebSocket upgrades.

Two properties fall out of that. The certificate stops being an anomaly, and an
active prober that connects to the endpoint (or even guesses the path with a
plain GET) is served the decoy site rather than a wstunnel 400.

Config layout is deliberately additive: OutWarp owns
``/etc/caddy/conf.d/outwarp.caddyfile`` and never rewrites a Caddyfile it did not
write. All it needs from the main one is a single ``import`` line, which it
appends if missing — servers that already run Caddy for other sites keep working.
"""

from __future__ import annotations

import logging
import shutil
import subprocess
from pathlib import Path

log = logging.getLogger(__name__)

CADDYFILE_MAIN = Path("/etc/caddy/Caddyfile")
CADDY_CONF_D = Path("/etc/caddy/conf.d")
CADDY_SITE_FILE = CADDY_CONF_D / "outwarp.caddyfile"
IMPORT_LINE = "import /etc/caddy/conf.d/*.caddyfile"
DEFAULT_DECOY_DIR = Path("/var/www/outwarp-decoy")

# wstunnel's loopback listener in this branch. Not exposed publicly — Caddy is
# the only thing that ever connects to it.
DEFAULT_INTERNAL_WS_PORT = 8080


class CaddyError(RuntimeError):
    pass


def find_caddy() -> Path | None:
    found = shutil.which("caddy")
    return Path(found) if found else None


def install_hint() -> str:
    """Per-distro install command, mirroring the doctor's remediation style."""
    if shutil.which("apt"):
        return (
            "sudo apt install -y debian-keyring debian-archive-keyring "
            "apt-transport-https curl && "
            "curl -1sLf 'https://dl.cloudsmith.io/public/caddy/stable/gpg.key' "
            "| sudo gpg --dearmor -o /usr/share/keyrings/caddy-stable-archive-keyring.gpg && "
            "curl -1sLf 'https://dl.cloudsmith.io/public/caddy/stable/debian.deb.txt' "
            "| sudo tee /etc/apt/sources.list.d/caddy-stable.list && "
            "sudo apt update && sudo apt install caddy"
        )
    if shutil.which("dnf"):
        return "sudo dnf install -y 'dnf-command(copr)' && sudo dnf copr enable -y @caddy/caddy && sudo dnf install -y caddy"  # noqa: E501
    if shutil.which("pacman"):
        return "sudo pacman -S --noconfirm caddy"
    if shutil.which("zypper"):
        return "sudo zypper install -y caddy"
    if shutil.which("apk"):
        return "sudo apk add caddy"
    return "See https://caddyserver.com/docs/install for your distribution."


def build_site_config(
    domain: str,
    upgrade_path: str,
    *,
    internal_ws_port: int = DEFAULT_INTERNAL_WS_PORT,
    decoy_dir: Path = DEFAULT_DECOY_DIR,
    acme_email: str = "",
    enroll_port: int = 0,
) -> str:
    """Render the Caddy site block that fronts wstunnel for `domain`.

    The tunnel matcher requires the secret path *and* a genuine WebSocket
    upgrade, so a prober who learns the path still only sees the decoy site.
    Caddy obtains and renews the certificate itself; ``acme_email`` only sets the
    ACME account contact address, which is optional.

    ``enroll_port`` publishes the enrolment endpoint on the same public port
    under a sibling of the secret path, so admitting new clients costs no extra
    open port in this branch.
    """
    if not domain:
        raise CaddyError("A domain is required to build the Caddy site config")
    if not upgrade_path:
        raise CaddyError("The http upgrade path prefix is required")

    header = ""
    if acme_email:
        header = f"{{\n\temail {acme_email}\n}}\n\n"

    path = upgrade_path.strip("/")
    enroll_block = ""
    if enroll_port:
        enroll_block = (
            f"\n\t@enroll path /{path}-enroll\n"
            f"\treverse_proxy @enroll 127.0.0.1:{enroll_port}\n"
        )
    return f"""\
{header}# Managed by OutWarp — regenerated by `outwarp-server setup`.
# Edits here are overwritten; put unrelated sites in their own conf.d file.
{domain} {{
\t@outwarp {{
\t\tpath /{path} /{path}/*
\t\theader Connection *Upgrade*
\t\theader Upgrade websocket
\t}}
\treverse_proxy @outwarp 127.0.0.1:{internal_ws_port}
{enroll_block}
\troot * {decoy_dir}
\tfile_server
}}
"""


DECOY_INDEX = """\
<!doctype html>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>It works!</title>
<style>
  :root { color-scheme: light dark; }
  body {
    font: 16px/1.6 system-ui, -apple-system, "Segoe UI", Roboto, sans-serif;
    margin: 0; min-height: 100vh; display: grid; place-items: center;
    padding: 2rem;
  }
  main { max-width: 34rem; }
  h1 { font-size: 1.5rem; margin: 0 0 .75rem; font-weight: 600; }
  p { margin: 0 0 1rem; opacity: .8; }
  code { font-family: ui-monospace, SFMono-Regular, Menlo, monospace; font-size: .9em; }
</style>
<main>
  <h1>It works!</h1>
  <p>
    This is the default page for this server. The web server software is running
    but no content has been added yet.
  </p>
  <p>
    If you maintain this site, replace <code>index.html</code> in the document
    root with your own content.
  </p>
</main>
"""


def write_decoy_site(decoy_dir: Path = DEFAULT_DECOY_DIR) -> Path:
    """Create the placeholder site served at ``/``.

    Deliberately a generic "default page" rather than anything resembling a real
    organisation: it has to look unremarkable, not impersonate anybody. Never
    overwrites an existing index — an admin who put real content there means it.
    """
    index = decoy_dir / "index.html"
    if index.exists():
        return index
    try:
        decoy_dir.mkdir(parents=True, exist_ok=True)
        index.write_text(DECOY_INDEX, encoding="utf-8")
    except OSError as exc:
        raise CaddyError(f"Could not write the decoy site to {decoy_dir}: {exc}") from exc
    return index


def ensure_import(main_caddyfile: Path = CADDYFILE_MAIN) -> bool:
    """Make sure the main Caddyfile pulls in ``conf.d``. Returns True if changed.

    Appends rather than rewrites: a box already serving other sites through Caddy
    must come out of this with its configuration intact.
    """
    try:
        if main_caddyfile.exists():
            text = main_caddyfile.read_text(encoding="utf-8")
            if IMPORT_LINE in text:
                return False
            suffix = "" if text.endswith("\n") else "\n"
            main_caddyfile.write_text(
                f"{text}{suffix}\n# Added by OutWarp\n{IMPORT_LINE}\n", encoding="utf-8"
            )
        else:
            main_caddyfile.parent.mkdir(parents=True, exist_ok=True)
            main_caddyfile.write_text(
                f"# Created by OutWarp\n{IMPORT_LINE}\n", encoding="utf-8"
            )
    except OSError as exc:
        raise CaddyError(f"Could not update {main_caddyfile}: {exc}") from exc
    return True


def write_site_config(text: str, site_file: Path = CADDY_SITE_FILE) -> Path:
    try:
        site_file.parent.mkdir(parents=True, exist_ok=True)
        site_file.write_text(text, encoding="utf-8")
    except OSError as exc:
        raise CaddyError(f"Could not write {site_file}: {exc}") from exc
    return site_file


def validate(main_caddyfile: Path = CADDYFILE_MAIN) -> tuple[bool, str]:
    """Run ``caddy validate`` so a bad config is caught before the reload."""
    caddy = find_caddy()
    if caddy is None:
        return False, "caddy is not installed"
    try:
        result = subprocess.run(
            [str(caddy), "validate", "--config", str(main_caddyfile)],
            capture_output=True, text=True, check=False, timeout=30,
        )
    except (OSError, subprocess.TimeoutExpired) as exc:
        return False, str(exc)
    if result.returncode == 0:
        return True, ""
    return False, (result.stderr or result.stdout).strip()


def reload_service() -> tuple[bool, str]:
    """Reload Caddy, preferring systemd and falling back to ``caddy reload``.

    A reload rather than a restart: Caddy applies the new config without
    dropping the connections it is already carrying.
    """
    if shutil.which("systemctl"):
        try:
            result = subprocess.run(
                ["systemctl", "reload", "caddy"],
                capture_output=True, text=True, check=False, timeout=30,
            )
        except (OSError, subprocess.TimeoutExpired) as exc:
            return False, str(exc)
        if result.returncode == 0:
            return True, ""
        # Not running yet (fresh install): reload fails but enable --now works.
        try:
            started = subprocess.run(
                ["systemctl", "enable", "--now", "caddy"],
                capture_output=True, text=True, check=False, timeout=60,
            )
        except (OSError, subprocess.TimeoutExpired) as exc:
            return False, str(exc)
        if started.returncode == 0:
            return True, ""
        return False, (started.stderr or result.stderr or "").strip()

    caddy = find_caddy()
    if caddy is None:
        return False, "caddy is not installed"
    try:
        result = subprocess.run(
            [str(caddy), "reload", "--config", str(CADDYFILE_MAIN)],
            capture_output=True, text=True, check=False, timeout=30,
        )
    except (OSError, subprocess.TimeoutExpired) as exc:
        return False, str(exc)
    return result.returncode == 0, (result.stderr or "").strip()


def apply(
    domain: str,
    upgrade_path: str,
    *,
    internal_ws_port: int = DEFAULT_INTERNAL_WS_PORT,
    decoy_dir: Path = DEFAULT_DECOY_DIR,
    acme_email: str = "",
    enroll_port: int = 0,
    main_caddyfile: Path = CADDYFILE_MAIN,
    site_file: Path = CADDY_SITE_FILE,
) -> list[str]:
    """Write the decoy site + site config, wire up the import, validate, reload.

    Returns human-readable warnings for the steps that degraded (a missing
    ``caddy`` binary, a reload that did not take). Raises CaddyError only when
    nothing usable was written at all — a config on disk that the admin can
    reload by hand is still a useful outcome.
    """
    warnings: list[str] = []
    write_decoy_site(decoy_dir)
    write_site_config(
        build_site_config(
            domain, upgrade_path,
            internal_ws_port=internal_ws_port, decoy_dir=decoy_dir,
            acme_email=acme_email, enroll_port=enroll_port,
        ),
        site_file,
    )
    ensure_import(main_caddyfile)

    if find_caddy() is None:
        warnings.append(
            f"caddy is not installed, so the config was written but not loaded. "
            f"Install it and run `systemctl reload caddy`:\n  {install_hint()}"
        )
        return warnings

    ok, detail = validate(main_caddyfile)
    if not ok:
        warnings.append(f"`caddy validate` rejected the configuration: {detail}")
        return warnings

    ok, detail = reload_service()
    if not ok:
        warnings.append(f"Caddy did not reload: {detail or 'unknown error'}")
    return warnings


def remove(
    main_caddyfile: Path = CADDYFILE_MAIN, site_file: Path = CADDY_SITE_FILE
) -> None:
    """Drop OutWarp's site config and reload. The import line is left alone —
    it is harmless, and other conf.d files may rely on it."""
    try:
        site_file.unlink(missing_ok=True)
    except OSError as exc:
        raise CaddyError(f"Could not remove {site_file}: {exc}") from exc
    if find_caddy() is not None:
        reload_service()
