// i18n + shared UI primitives for OutWarp

const STR = {
  es: {
    // Empty state
    welcomeTitle: "Conéctate a tu túnel",
    welcomeSub: "Importa un archivo de configuración .owcfg que te haya enviado tu servidor.",
    importFile: "Importar archivo",
    importDrop: "Arrastra el .owcfg aquí",
    importPaste: "o pega el contenido",
    importQR: "Escanear QR",
    importHint: "Formato soportado: .owcfg generado por outwarp-server add-client",

    // States
    disconnected: "Desconectado",
    connecting: "Conectando…",
    handshake: "Handshake WireGuard",
    reconnecting: "Reconectando",
    connected: "Conectado",
    error: "Error de conexión",

    // Big actions
    connect: "Conectar",
    disconnect: "Desconectar",
    cancel: "Cancelar",

    // Stats
    publicIp: "IP pública",
    location: "Ubicación",
    latency: "Latencia",
    upload: "Subida",
    download: "Bajada",
    transferred: "Transferido",
    sessionTime: "Tiempo de sesión",
    lastHandshake: "Último handshake",
    endpoint: "Endpoint",
    fingerprint: "Huella TLS",

    // Nav / sections
    nav_home: "Conexión",
    nav_profiles: "Perfiles",
    nav_logs: "Registro",
    nav_settings: "Ajustes",
    nav_about: "Acerca de",

    // Settings
    set_killSwitch: "Kill switch",
    set_killSwitchSub: "Bloquea internet si la VPN se cae",
    set_autoconnect: "Conexión automática al iniciar",
    set_autoconnectSub: "Inicia el túnel cuando se abra Windows",
    set_splitTunnel: "Split tunnel",
    set_splitTunnelSub: "Decide qué apps van por el túnel",
    set_startup: "Iniciar al arrancar Windows",
    set_minimizeTray: "Minimizar a la bandeja",
    set_advanced: "Modo avanzado",
    set_advancedSub: "Mostrar IPs, claves y huella del certificado",
    set_dns: "DNS personalizado",
    set_mtu: "MTU",
    set_language: "Idioma",
    set_theme: "Tema",
    set_themeAuto: "Automático",
    set_themeLight: "Claro",
    set_themeDark: "Oscuro",

    // Logs
    logs_title: "Registro de actividad",
    logs_clear: "Limpiar",
    logs_export: "Exportar",
    logs_filter: "Filtrar…",

    // Profiles
    profiles_title: "Perfiles",
    profiles_add: "Añadir perfil",
    profiles_active: "Activo",

    // Profile editor
    edit_title: "Ajustes del perfil",
    edit_sub: "Valores de conexión asignados por tu servidor.",
    edit_open: "Editar ajustes",
    edit_disclaimerTitle: "Estás a punto de editar la configuración",
    edit_disclaimerBody: "Estos valores vienen de tu servidor y normalmente no necesitan cambiarse. Una configuración incorrecta puede impedir que el túnel conecte. Si algo deja de funcionar, usa «Reiniciar a predeterminados».",
    edit_disclaimerAck: "Entiendo, quiero editar",
    edit_name: "Nombre del perfil",
    edit_mtu: "MTU",
    edit_mtuHint: "Entre 576 y 1500. Por defecto 1380.",
    edit_dns: "Servidores DNS",
    edit_dnsHint: "Separados por comas.",
    edit_clientIp: "IP del cliente",
    edit_clientIpHint: "Debe coincidir con la asignada en el servidor (ej. 10.0.0.2/32).",
    edit_bypass: "IPs de bypass",
    edit_bypassHint: "Rutas excluidas del túnel. Separadas por comas.",
    edit_maxAttempts: "Reintentos de reconexión",
    edit_delays: "Tiempos de reconexión (s)",
    edit_delaysHint: "Segundos entre reintentos, separados por comas.",
    edit_save: "Guardar cambios",
    edit_reset: "Reiniciar a predeterminados",
    edit_cancel: "Cancelar",
    edit_reconnectNote: "El túnel se reconectará automáticamente para aplicar los cambios.",
    edit_saved: "✓ Ajustes guardados",
    edit_resetDone: "✓ Ajustes restaurados a los valores originales",
    edit_resetConfirm: "¿Restaurar todos los ajustes a como estaban al importar el perfil? Se perderán los cambios locales.",

    // Connecting steps
    step_resolve: "Resolviendo endpoint",
    step_tls: "Verificando certificado",
    step_ws: "Estableciendo WebSocket",
    step_wg: "Negociando WireGuard",
    step_route: "Aplicando rutas",
    step_done: "Listo",

    // Misc
    profile: "Perfil",
    home_ribbon: "Tu tráfico viaja cifrado por wstunnel → WireGuard.",
    notConnected: "Sin túnel activo",
    showAdvanced: "Mostrar detalles técnicos",
    hideAdvanced: "Ocultar detalles técnicos",
  },
  en: {
    welcomeTitle: "Connect to your tunnel",
    welcomeSub: "Import a .owcfg configuration file shared by your server.",
    importFile: "Import file",
    importDrop: "Drop your .owcfg here",
    importPaste: "or paste contents",
    importQR: "Scan QR",
    importHint: "Supported format: .owcfg generated by outwarp-server add-client",

    disconnected: "Disconnected",
    connecting: "Connecting…",
    handshake: "WireGuard handshake",
    reconnecting: "Reconnecting",
    connected: "Connected",
    error: "Connection error",

    connect: "Connect",
    disconnect: "Disconnect",
    cancel: "Cancel",

    publicIp: "Public IP",
    location: "Location",
    latency: "Latency",
    upload: "Upload",
    download: "Download",
    transferred: "Transferred",
    sessionTime: "Session time",
    lastHandshake: "Last handshake",
    endpoint: "Endpoint",
    fingerprint: "TLS fingerprint",

    nav_home: "Connection",
    nav_profiles: "Profiles",
    nav_logs: "Logs",
    nav_settings: "Settings",
    nav_about: "About",

    set_killSwitch: "Kill switch",
    set_killSwitchSub: "Block internet if VPN drops",
    set_autoconnect: "Auto-connect on launch",
    set_autoconnectSub: "Bring up the tunnel when Windows starts",
    set_splitTunnel: "Split tunnel",
    set_splitTunnelSub: "Choose which apps go through the tunnel",
    set_startup: "Start with Windows",
    set_minimizeTray: "Minimize to system tray",
    set_advanced: "Advanced mode",
    set_advancedSub: "Show IPs, keys and certificate fingerprint",
    set_dns: "Custom DNS",
    set_mtu: "MTU",
    set_language: "Language",
    set_theme: "Theme",
    set_themeAuto: "Auto",
    set_themeLight: "Light",
    set_themeDark: "Dark",

    logs_title: "Activity log",
    logs_clear: "Clear",
    logs_export: "Export",
    logs_filter: "Filter…",

    profiles_title: "Profiles",
    profiles_add: "Add profile",
    profiles_active: "Active",

    edit_title: "Profile settings",
    edit_sub: "Connection values assigned by your server.",
    edit_open: "Edit settings",
    edit_disclaimerTitle: "You're about to edit the configuration",
    edit_disclaimerBody: "These values come from your server and rarely need changing. A wrong setting can stop the tunnel from connecting. If something breaks, use “Reset to defaults”.",
    edit_disclaimerAck: "I understand, let me edit",
    edit_name: "Profile name",
    edit_mtu: "MTU",
    edit_mtuHint: "Between 576 and 1500. Default 1380.",
    edit_dns: "DNS servers",
    edit_dnsHint: "Comma-separated.",
    edit_clientIp: "Client IP",
    edit_clientIpHint: "Must match the address assigned on the server (e.g. 10.0.0.2/32).",
    edit_bypass: "Bypass IPs",
    edit_bypassHint: "Routes excluded from the tunnel. Comma-separated.",
    edit_maxAttempts: "Reconnect attempts",
    edit_delays: "Reconnect delays (s)",
    edit_delaysHint: "Seconds between retries, comma-separated.",
    edit_save: "Save changes",
    edit_reset: "Reset to defaults",
    edit_cancel: "Cancel",
    edit_reconnectNote: "The tunnel will reconnect automatically to apply the changes.",
    edit_saved: "✓ Settings saved",
    edit_resetDone: "✓ Settings restored to their original values",
    edit_resetConfirm: "Restore all settings to how they were when the profile was imported? Local changes will be lost.",

    step_resolve: "Resolving endpoint",
    step_tls: "Verifying certificate",
    step_ws: "Establishing WebSocket",
    step_wg: "Negotiating WireGuard",
    step_route: "Applying routes",
    step_done: "Done",

    profile: "Profile",
    home_ribbon: "Your traffic is encrypted via wstunnel → WireGuard.",
    notConnected: "No active tunnel",
    showAdvanced: "Show technical details",
    hideAdvanced: "Hide technical details",
  },
};

// realistic log lines used by both variations
const SAMPLE_LOGS = [
  { t: "12:04:02.118", lvl: "info",  msg: "outwarp client v0.4.2 starting" },
  { t: "12:04:02.221", lvl: "info",  msg: "loading profile 'Universidad' from %APPDATA%\\OutWarp" },
  { t: "12:04:02.310", lvl: "debug", msg: "wstunnel target = wss://vps.fcrespo.dev:443" },
  { t: "12:04:02.402", lvl: "info",  msg: "resolving vps.fcrespo.dev → 89.32.144.19" },
  { t: "12:04:02.566", lvl: "debug", msg: "TLS cert sha256 fingerprint: 4f:9a:1c:7e:b3:d2:8a:55:…" },
  { t: "12:04:02.567", lvl: "info",  msg: "fingerprint matches pinned value ✓" },
  { t: "12:04:02.701", lvl: "info",  msg: "WebSocket established (HTTP/1.1 → 101 Switching Protocols)" },
  { t: "12:04:02.840", lvl: "info",  msg: "wg-quick: bringing up interface outwarp0" },
  { t: "12:04:03.002", lvl: "info",  msg: "added route 89.32.144.19/32 → 192.168.1.1 (bypass)" },
  { t: "12:04:03.219", lvl: "debug", msg: "WG: sending initial handshake" },
  { t: "12:04:03.401", lvl: "info",  msg: "WG handshake OK (rtt=182ms)" },
  { t: "12:04:03.402", lvl: "info",  msg: "tunnel UP — peer 10.66.0.1, allowed-ips 0.0.0.0/0" },
  { t: "12:05:18.712", lvl: "debug", msg: "rx 4.2 MB · tx 812 KB · last_hs=00:01:15" },
  { t: "12:07:44.114", lvl: "debug", msg: "rx 19.7 MB · tx 2.1 MB · last_hs=00:00:42" },
];

window.STR = STR;
window.SAMPLE_LOGS = SAMPLE_LOGS;

// hook to read tweaks from a parent
const useUiState = (initial) => {
  const [state, setState] = React.useState(initial);
  return [state, (k, v) => setState((s) => ({ ...s, [k]: typeof k === "object" ? { ...s, ...k } : v ?? s[k] })), setState];
};
window.useUiState = useUiState;

// Tiny atoms shared by both variations
const Btn = ({ children, kind = "ghost", size = "md", icon, style = {}, ...rest }) => {
  const sizes = {
    sm: { h: 28, px: 10, fs: 12, r: 6 },
    md: { h: 36, px: 14, fs: 13, r: 8 },
    lg: { h: 44, px: 18, fs: 14, r: 10 },
  }[size];
  const palettes = {
    primary: { bg: "var(--brand)", color: "#fff", border: "var(--brand)" },
    ghost:   { bg: "transparent", color: "var(--text)", border: "var(--line-strong)" },
    soft:    { bg: "var(--chip)", color: "var(--text)", border: "transparent" },
    danger:  { bg: "transparent", color: "var(--brand-bad)", border: "var(--line-strong)" },
    solid:   { bg: "var(--text)", color: "var(--bg)", border: "var(--text)" },
  }[kind];
  return (
    <button {...rest}
      style={{
        height: sizes.h,
        padding: `0 ${sizes.px}px`,
        borderRadius: sizes.r,
        background: palettes.bg,
        color: palettes.color,
        border: `1px solid ${palettes.border}`,
        fontFamily: "var(--font-sans)",
        fontSize: sizes.fs,
        fontWeight: 500,
        letterSpacing: "-0.005em",
        cursor: "pointer",
        display: "inline-flex",
        alignItems: "center",
        gap: 8,
        whiteSpace: "nowrap",
        ...style,
      }}
    >
      {icon}{children}
    </button>
  );
};

const Pill = ({ children, tone = "neutral", style = {} }) => {
  const tones = {
    neutral: { bg: "var(--chip)", fg: "var(--text-2)" },
    good:    { bg: "color-mix(in srgb, var(--brand-2) 16%, transparent)", fg: "var(--brand-2)" },
    bad:     { bg: "color-mix(in srgb, var(--brand-bad) 16%, transparent)", fg: "var(--brand-bad)" },
    warn:    { bg: "color-mix(in srgb, var(--brand-warn) 18%, transparent)", fg: "var(--brand-warn)" },
    brand:   { bg: "color-mix(in srgb, var(--brand) 16%, transparent)", fg: "var(--brand)" },
  }[tone];
  return (
    <span style={{ display: "inline-flex", alignItems: "center", gap: 6, height: 22, padding: "0 8px", borderRadius: 999, fontSize: 11, fontWeight: 500, fontFamily: "var(--font-mono)", background: tones.bg, color: tones.fg, ...style }}>
      {children}
    </span>
  );
};

const StatusDot = ({ tone = "good", pulse = true }) => {
  const c = tone === "good" ? "var(--brand-2)" : tone === "bad" ? "var(--brand-bad)" : tone === "warn" ? "var(--brand-warn)" : "var(--text-3)";
  return (
    <span style={{ position: "relative", display: "inline-block", width: 8, height: 8 }}>
      {pulse ? <span style={{ position: "absolute", inset: 0, borderRadius: 999, background: c, animation: "ws-pulse 1.6s ease-out infinite" }}/> : null}
      <span style={{ position: "absolute", inset: 0, borderRadius: 999, background: c }}/>
    </span>
  );
};

const Toggle = ({ on, onChange, accent }) => (
  <button onClick={() => onChange?.(!on)} aria-pressed={on}
    style={{
      width: 36, height: 20, borderRadius: 999, padding: 2, border: "none",
      background: on ? (accent || "var(--brand)") : "var(--line-strong)",
      cursor: "pointer", display: "inline-flex", alignItems: "center",
      transition: "background .15s",
    }}>
    <span style={{ width: 16, height: 16, borderRadius: 999, background: "#fff",
      transform: on ? "translateX(16px)" : "translateX(0)", transition: "transform .15s",
      boxShadow: "0 1px 2px rgba(0,0,0,.25)" }}/>
  </button>
);

window.Btn = Btn;
window.Pill = Pill;
window.StatusDot = StatusDot;
window.Toggle = Toggle;
