"""Pre-compile the client and server JSX bundles.

The OutWarp UIs used to ship Babel-standalone (3.1 MB) plus 6–7 JSX
files that were transpiled in-browser on every cold start. That added
1–3 s to "open window" on modest machines and made the packaged .exe
unnecessarily large. This script transpiles + concatenates the JSX
into a single bundle.js per side, ahead of time, using esbuild.

Run it whenever you edit any .jsx under client/outwarp/ui/ or
server/outwarp_server/ui/ — the generated bundle.js files are
committed so end users don't need Node to run from source.

Usage:
    python scripts/build_ui.py            # build both bundles
    python scripts/build_ui.py client     # build only client
    python scripts/build_ui.py server     # build only server
    python scripts/build_ui.py --check    # fail if a committed bundle is stale

Requires Node.js on PATH. esbuild is pinned (ESBUILD_VERSION, kept equal to
package.json): the local node_modules copy after `npm ci`, otherwise npx
fetches that exact version. The bundle is only reproducible — and the
`--check` guard in CI only meaningful — with one esbuild version.
"""

from __future__ import annotations

import shutil
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
CLIENT_UI = ROOT / "client" / "outwarp" / "ui"
SERVER_UI = ROOT / "server" / "outwarp_server" / "ui"

# Must match devDependencies.esbuild in package.json (ui-tests/ checks it).
ESBUILD_VERSION = "0.28.2"
_LOCAL_ESBUILD = ROOT / "node_modules" / ".bin" / (
    "esbuild.cmd" if sys.platform == "win32" else "esbuild"
)

# Order matters: each file relies on globals defined by previous ones
# (React hooks, STR, Btn/Pill/StatusDot atoms).
CLIENT_ORDER = ["brand.jsx", "shared.jsx", "app.jsx"]
SERVER_ORDER = [
    # Unified server dashboard (desktop pywebview + remote web panel). The
    # transport shim must come first (app.jsx reads window.OW); the old
    # srv-a/srv-b desktop GUI was replaced by this dash-* set.
    "transport.js",
    "brand.jsx",
    "dash-data.jsx",
    "dash-atoms.jsx",
    "dash-screens.jsx",
    "dash-extras.jsx",
    "app.jsx",
]

PROLOG = (
    "// Auto-generated by scripts/build_ui.py — do not edit by hand.\n"
    "// Edit the .jsx sources in this folder and re-run the build.\n"
    "\n"
    "// Pass-through replacement for the design canvas' WindowsFrame.\n"
    "// The native pywebview window already provides chrome.\n"
    'window.WindowsFrame = ({ children }) => '
    '<div style={{ height: "100%", width: "100%" }}>{children}</div>;\n'
)


def _esbuild_cmd() -> list[str]:
    """The pinned esbuild: node_modules' copy if present, else npx.

    On Windows the shell must resolve `npx.cmd` / `esbuild.cmd`, hence
    shell=True downstream."""
    flags = ["--loader=jsx", "--minify", "--target=es2020", "--log-level=warning"]
    if _LOCAL_ESBUILD.exists():
        return [str(_LOCAL_ESBUILD), *flags]
    if shutil.which("npx") is None:
        raise SystemExit(
            "error: npx not found on PATH. Install Node.js 20+ "
            "(https://nodejs.org/) and re-run this script. Node is only "
            "needed to *build* the UI; end users running the packaged "
            "binary do not need it."
        )
    return ["npx", "--yes", f"esbuild@{ESBUILD_VERSION}", *flags]


def build(ui_dir: Path, order: list[str], *, check: bool = False) -> bool:
    """Build ui_dir/bundle.js; with ``check``, only compare. Returns whether
    the committed bundle is (or now is) up to date."""
    print(f"[build_ui] {ui_dir.relative_to(ROOT)}")
    parts = [PROLOG]
    for name in order:
        src = (ui_dir / name).read_text(encoding="utf-8")
        # Each .jsx file used to be its own <script>, so top-level const/let
        # bindings were script-scoped (two files may both declare
        # `const Stat = ...` without colliding). Wrapping each file in an
        # IIFE preserves that scoping after concatenation. Anything the file
        # explicitly exposes (window.STR = STR, etc.)
        # still becomes global because `window.*` writes go to the host.
        parts.append(
            f"\n// ==== {name} ====\n;(function(){{\n{src}\n}})();\n"
        )
    combined = "".join(parts).encode("utf-8")

    cmd = _esbuild_cmd()
    result = subprocess.run(
        cmd,
        input=combined,
        capture_output=True,
        shell=(sys.platform == "win32"),
    )
    if result.returncode != 0:
        sys.stderr.write(result.stderr.decode("utf-8", errors="replace"))
        raise SystemExit(f"esbuild failed with exit {result.returncode}")

    out_path = ui_dir / "bundle.js"
    if check:
        current = out_path.read_bytes() if out_path.exists() else b""
        if current != result.stdout:
            print(f"  !! {out_path.relative_to(ROOT)} is stale: run python scripts/build_ui.py")
            return False
        print("  ok: bundle.js matches its sources")
        return True
    out_path.write_bytes(result.stdout)
    raw_kb = sum(len(p.encode("utf-8")) for p in parts) // 1024
    out_kb = len(result.stdout) // 1024
    print(f"  -> bundle.js ({out_kb} KB, from {raw_kb} KB of JSX)")
    return True


def main() -> int:
    args = sys.argv[1:]
    check = "--check" in args
    targets = [a for a in args if a != "--check"] or ["client", "server"]
    ok = True
    for t in targets:
        if t == "client":
            ok &= build(CLIENT_UI, CLIENT_ORDER, check=check)
        elif t == "server":
            ok &= build(SERVER_UI, SERVER_ORDER, check=check)
        else:
            raise SystemExit(f"unknown target '{t}' (expected 'client' or 'server')")
    return 0 if ok else 1


if __name__ == "__main__":
    sys.exit(main())
