// i18n + shared UI primitives for OutWarp

const STR = {
  es: {
    // Empty state
    welcomeTitle: "Conéctate a tu túnel",
    welcomeSub: "Importa un archivo de configuración .owcfg que te haya enviado tu servidor.",
    importFile: "Importar archivo",
    importDrop: "Arrastra el .owcfg aquí",
    importPaste: "o pega el contenido",
    importQR: "Escanear QR",
    importHint: "Formato soportado: .owcfg generado por outwarp-server add-client",

    // States
    disconnected: "Desconectado",
    connecting: "Conectando…",
    handshake: "Handshake WireGuard",
    reconnecting: "Reconectando",
    connected: "Conectado",
    error: "Error de conexión",

    // Big actions
    connect: "Conectar",
    disconnect: "Desconectar",
    cancel: "Cancelar",

    // Stats
    publicIp: "IP pública",
    location: "Ubicación",
    latency: "Latencia",
    upload: "Subida",
    download: "Bajada",
    transferred: "Transferido",
    sessionTime: "Tiempo de sesión",
    lastHandshake: "Último handshake",
    endpoint: "Endpoint",
    fingerprint: "Huella TLS",

    // Nav / sections
    nav_home: "Conexión",
    nav_profiles: "Perfiles",
    nav_logs: "Registro",
    nav_settings: "Ajustes",
    nav_about: "Acerca de",

    // Settings
    set_killSwitch: "Kill switch",
    set_killSwitchSub: "Bloquea internet si la VPN se cae",
    set_autoconnect: "Conexión automática al iniciar",
    set_autoconnectSub: "Inicia el túnel cuando se abra Windows",
    set_splitTunnel: "Split tunnel",
    set_splitTunnelSub: "Decide qué apps van por el túnel",
    set_startup: "Iniciar al arrancar Windows",
    set_minimizeTray: "Minimizar a la bandeja",
    set_advanced: "Modo avanzado",
    set_advancedSub: "Mostrar IPs, claves y huella del certificado",
    set_dns: "DNS personalizado",
    set_mtu: "MTU",
    set_language: "Idioma",
    set_theme: "Tema",
    set_themeAuto: "Automático",
    set_themeLight: "Claro",
    set_themeDark: "Oscuro",

    // Logs
    logs_title: "Registro de actividad",
    logs_clear: "Limpiar",
    logs_export: "Exportar",
    logs_filter: "Filtrar…",

    // Profiles
    profiles_title: "Perfiles",
    profiles_add: "Añadir perfil",
    profiles_active: "Activo",

    // Connecting steps
    step_resolve: "Resolviendo endpoint",
    step_tls: "Verificando certificado",
    step_ws: "Estableciendo WebSocket",
    step_wg: "Negociando WireGuard",
    step_route: "Aplicando rutas",
    step_done: "Listo",

    // Misc
    profile: "Perfil",
    home_ribbon: "Tu tráfico viaja cifrado por wstunnel → WireGuard.",
    notConnected: "Sin túnel activo",
    showAdvanced: "Mostrar detalles técnicos",
    hideAdvanced: "Ocultar detalles técnicos",
  },
  en: {
    welcomeTitle: "Connect to your tunnel",
    welcomeSub: "Import a .owcfg configuration file shared by your server.",
    importFile: "Import file",
    importDrop: "Drop your .owcfg here",
    importPaste: "or paste contents",
    importQR: "Scan QR",
    importHint: "Supported format: .owcfg generated by outwarp-server add-client",

    disconnected: "Disconnected",
    connecting: "Connecting…",
    handshake: "WireGuard handshake",
    reconnecting: "Reconnecting",
    connected: "Connected",
    error: "Connection error",

    connect: "Connect",
    disconnect: "Disconnect",
    cancel: "Cancel",

    publicIp: "Public IP",
    location: "Location",
    latency: "Latency",
    upload: "Upload",
    download: "Download",
    transferred: "Transferred",
    sessionTime: "Session time",
    lastHandshake: "Last handshake",
    endpoint: "Endpoint",
    fingerprint: "TLS fingerprint",

    nav_home: "Connection",
    nav_profiles: "Profiles",
    nav_logs: "Logs",
    nav_settings: "Settings",
    nav_about: "About",

    set_killSwitch: "Kill switch",
    set_killSwitchSub: "Block internet if VPN drops",
    set_autoconnect: "Auto-connect on launch",
    set_autoconnectSub: "Bring up the tunnel when Windows starts",
    set_splitTunnel: "Split tunnel",
    set_splitTunnelSub: "Choose which apps go through the tunnel",
    set_startup: "Start with Windows",
    set_minimizeTray: "Minimize to system tray",
    set_advanced: "Advanced mode",
    set_advancedSub: "Show IPs, keys and certificate fingerprint",
    set_dns: "Custom DNS",
    set_mtu: "MTU",
    set_language: "Language",
    set_theme: "Theme",
    set_themeAuto: "Auto",
    set_themeLight: "Light",
    set_themeDark: "Dark",

    logs_title: "Activity log",
    logs_clear: "Clear",
    logs_export: "Export",
    logs_filter: "Filter…",

    profiles_title: "Profiles",
    profiles_add: "Add profile",
    profiles_active: "Active",

    step_resolve: "Resolving endpoint",
    step_tls: "Verifying certificate",
    step_ws: "Establishing WebSocket",
    step_wg: "Negotiating WireGuard",
    step_route: "Applying routes",
    step_done: "Done",

    profile: "Profile",
    home_ribbon: "Your traffic is encrypted via wstunnel → WireGuard.",
    notConnected: "No active tunnel",
    showAdvanced: "Show technical details",
    hideAdvanced: "Hide technical details",
  },
};

// realistic log lines used by both variations
const SAMPLE_LOGS = [
  { t: "12:04:02.118", lvl: "info",  msg: "outwarp client v0.4.2 starting" },
  { t: "12:04:02.221", lvl: "info",  msg: "loading profile 'Universidad' from %APPDATA%\\OutWarp" },
  { t: "12:04:02.310", lvl: "debug", msg: "wstunnel target = wss://vps.fcrespo.dev:443" },
  { t: "12:04:02.402", lvl: "info",  msg: "resolving vps.fcrespo.dev → 89.32.144.19" },
  { t: "12:04:02.566", lvl: "debug", msg: "TLS cert sha256 fingerprint: 4f:9a:1c:7e:b3:d2:8a:55:…" },
  { t: "12:04:02.567", lvl: "info",  msg: "fingerprint matches pinned value ✓" },
  { t: "12:04:02.701", lvl: "info",  msg: "WebSocket established (HTTP/1.1 → 101 Switching Protocols)" },
  { t: "12:04:02.840", lvl: "info",  msg: "wg-quick: bringing up interface outwarp0" },
  { t: "12:04:03.002", lvl: "info",  msg: "added route 89.32.144.19/32 → 192.168.1.1 (bypass)" },
  { t: "12:04:03.219", lvl: "debug", msg: "WG: sending initial handshake" },
  { t: "12:04:03.401", lvl: "info",  msg: "WG handshake OK (rtt=182ms)" },
  { t: "12:04:03.402", lvl: "info",  msg: "tunnel UP — peer 10.66.0.1, allowed-ips 0.0.0.0/0" },
  { t: "12:05:18.712", lvl: "debug", msg: "rx 4.2 MB · tx 812 KB · last_hs=00:01:15" },
  { t: "12:07:44.114", lvl: "debug", msg: "rx 19.7 MB · tx 2.1 MB · last_hs=00:00:42" },
];

window.STR = STR;
window.SAMPLE_LOGS = SAMPLE_LOGS;

// hook to read tweaks from a parent
const useUiState = (initial) => {
  const [state, setState] = React.useState(initial);
  return [state, (k, v) => setState((s) => ({ ...s, [k]: typeof k === "object" ? { ...s, ...k } : v ?? s[k] })), setState];
};
window.useUiState = useUiState;

// Tiny atoms shared by both variations
const Btn = ({ children, kind = "ghost", size = "md", icon, style = {}, ...rest }) => {
  const sizes = {
    sm: { h: 28, px: 10, fs: 12, r: 6 },
    md: { h: 36, px: 14, fs: 13, r: 8 },
    lg: { h: 44, px: 18, fs: 14, r: 10 },
  }[size];
  const palettes = {
    primary: { bg: "var(--brand)", color: "#fff", border: "var(--brand)" },
    ghost:   { bg: "transparent", color: "var(--text)", border: "var(--line-strong)" },
    soft:    { bg: "var(--chip)", color: "var(--text)", border: "transparent" },
    danger:  { bg: "transparent", color: "var(--brand-bad)", border: "var(--line-strong)" },
    solid:   { bg: "var(--text)", color: "var(--bg)", border: "var(--text)" },
  }[kind];
  return (
    <button {...rest}
      style={{
        height: sizes.h,
        padding: `0 ${sizes.px}px`,
        borderRadius: sizes.r,
        background: palettes.bg,
        color: palettes.color,
        border: `1px solid ${palettes.border}`,
        fontFamily: "var(--font-sans)",
        fontSize: sizes.fs,
        fontWeight: 500,
        letterSpacing: "-0.005em",
        cursor: "pointer",
        display: "inline-flex",
        alignItems: "center",
        gap: 8,
        whiteSpace: "nowrap",
        ...style,
      }}
    >
      {icon}{children}
    </button>
  );
};

const Pill = ({ children, tone = "neutral", style = {} }) => {
  const tones = {
    neutral: { bg: "var(--chip)", fg: "var(--text-2)" },
    good:    { bg: "color-mix(in srgb, var(--brand-2) 16%, transparent)", fg: "var(--brand-2)" },
    bad:     { bg: "color-mix(in srgb, var(--brand-bad) 16%, transparent)", fg: "var(--brand-bad)" },
    warn:    { bg: "color-mix(in srgb, var(--brand-warn) 18%, transparent)", fg: "var(--brand-warn)" },
    brand:   { bg: "color-mix(in srgb, var(--brand) 16%, transparent)", fg: "var(--brand)" },
  }[tone];
  return (
    <span style={{ display: "inline-flex", alignItems: "center", gap: 6, height: 22, padding: "0 8px", borderRadius: 999, fontSize: 11, fontWeight: 500, fontFamily: "var(--font-mono)", background: tones.bg, color: tones.fg, ...style }}>
      {children}
    </span>
  );
};

const StatusDot = ({ tone = "good", pulse = true }) => {
  const c = tone === "good" ? "var(--brand-2)" : tone === "bad" ? "var(--brand-bad)" : tone === "warn" ? "var(--brand-warn)" : "var(--text-3)";
  return (
    <span style={{ position: "relative", display: "inline-block", width: 8, height: 8 }}>
      {pulse ? <span style={{ position: "absolute", inset: 0, borderRadius: 999, background: c, animation: "ws-pulse 1.6s ease-out infinite" }}/> : null}
      <span style={{ position: "absolute", inset: 0, borderRadius: 999, background: c }}/>
    </span>
  );
};

const Toggle = ({ on, onChange, accent }) => (
  <button onClick={() => onChange?.(!on)} aria-pressed={on}
    style={{
      width: 36, height: 20, borderRadius: 999, padding: 2, border: "none",
      background: on ? (accent || "var(--brand)") : "var(--line-strong)",
      cursor: "pointer", display: "inline-flex", alignItems: "center",
      transition: "background .15s",
    }}>
    <span style={{ width: 16, height: 16, borderRadius: 999, background: "#fff",
      transform: on ? "translateX(16px)" : "translateX(0)", transition: "transform .15s",
      boxShadow: "0 1px 2px rgba(0,0,0,.25)" }}/>
  </button>
);

// ── Crash recovery ─────────────────────────────────────────────────
// A render/lifecycle exception anywhere in the tree would otherwise blank the
// whole pywebview window with no way back (frameless = no native chrome). This
// boundary catches it, reports the stack to the Python log via the bridge, and
// shows a self-contained recovery screen so the user is never stuck. It uses
// only inline styles + design tokens — it must not depend on the components
// that may have just crashed.
const _ErrorScreen = ({ error }) => {
  const reload = () => { try { window.location.reload(); } catch (_) {} };
  const close = () => { try { window.pywebview?.api?.window_close?.(); } catch (_) {} };
  const startMove = (e) => { if (e.button === 0) { try { window.pywebview?.api?.window_start_move?.(); } catch (_) {} } };
  const detail = (error && (error.stack || error.message)) || String(error || "");
  return (
    <div style={{ height: "100%", display: "flex", flexDirection: "column", background: "var(--bg)", color: "var(--text)" }}>
      <div className="pywebview-drag-region" onMouseDown={startMove}
        style={{ flex: "0 0 38px", display: "flex", alignItems: "center", justifyContent: "flex-end", borderBottom: "1px solid var(--line)", background: "var(--bg-2)" }}>
        <button className="ow-winbtn close" onClick={close} title="Cerrar / Close" aria-label="Cerrar / Close">
          <svg width="11" height="11" viewBox="0 0 12 12" stroke="currentColor" strokeWidth="1.1"><line x1="2.5" y1="2.5" x2="9.5" y2="9.5"/><line x1="9.5" y1="2.5" x2="2.5" y2="9.5"/></svg>
        </button>
      </div>
      <div style={{ flex: 1, minHeight: 0, display: "grid", placeItems: "center", padding: 28 }}>
        <div style={{ maxWidth: 520, width: "100%" }}>
          <div style={{ fontSize: 20, fontWeight: 600, letterSpacing: "-0.02em" }}>Algo ha fallado · Something went wrong</div>
          <div style={{ fontSize: 13, color: "var(--text-2)", marginTop: 8 }}>
            La interfaz encontró un error inesperado. El servicio no se ve afectado — recarga la ventana para continuar.
            <br/>The interface hit an unexpected error. The service is unaffected — reload to continue.
          </div>
          <pre style={{ marginTop: 16, maxHeight: 180, overflow: "auto", background: "var(--bg-sunk)", border: "1px solid var(--line)", borderRadius: 8, padding: 12, fontFamily: "var(--font-mono)", fontSize: 11, color: "var(--text-2)", whiteSpace: "pre-wrap" }}>{detail}</pre>
          <div style={{ display: "flex", gap: 8, marginTop: 16 }}>
            <button onClick={reload} style={{ all: "unset", cursor: "pointer", padding: "9px 16px", borderRadius: 8, background: "var(--brand)", color: "#fff", fontSize: 13, fontWeight: 600 }}>Recargar · Reload</button>
            <button onClick={close} style={{ all: "unset", cursor: "pointer", padding: "9px 16px", borderRadius: 8, border: "1px solid var(--line-strong)", color: "var(--text)", fontSize: 13, fontWeight: 500 }}>Cerrar · Close</button>
          </div>
        </div>
      </div>
    </div>
  );
};

class ErrorBoundary extends React.Component {
  constructor(props) {
    super(props);
    this.state = { error: null };
  }
  static getDerivedStateFromError(error) {
    return { error };
  }
  componentDidCatch(error, info) {
    try {
      const where = (info && info.componentStack) || "";
      const msg = (error && (error.stack || error.message)) || String(error);
      window.pywebview?.api?.report_ui_error?.(`render crash: ${msg}\n${where}`.slice(0, 4000));
    } catch (_) {}
  }
  render() {
    if (this.state.error) return React.createElement(_ErrorScreen, { error: this.state.error });
    return this.props.children;
  }
}

window.Btn = Btn;
window.Pill = Pill;
window.StatusDot = StatusDot;
window.Toggle = Toggle;
window.ErrorBoundary = ErrorBoundary;
