apiVersion: v1
kind: Service
metadata:
  name: outwarp-server
spec:
  type: LoadBalancer
  selector:
    app: outwarp-server
  ports:
    - name: wss
      port: 443
      targetPort: 443
      protocol: TCP
